In [27]:
import pandas as pd
import numpy as np
import matplotlib as plt
import pyodbc

%matplotlib inline

pd.set_option('display.float_format', lambda x: '%.3f' % x)

con = pyodbc.connect('Trusted_Connection=yes', driver = '{SQL Server}',server = 'uslilvmdwprd1.delphiprd.am.joneslanglasalle.com', database = 'CDW_Capital_One_Services_LLC')

In [2]:
data = pd.read_csv('raw.csv', encoding='iso-8859-1')

In [3]:
data.head()

,Response ID,IP Address,Timestamp (MM/dd/yyyy),Duplicate,Time Taken to Complete (Seconds),Seq. Number,External Reference,Custom Variable 1,Custom Variable 2,Custom Variable 3,...,"Comment (If there are no comments, enter N/A) .3",Risk,Scale .4,"Comment (If there are no comments, enter N/A) .4",Professionalism,Scale .5,"Comment (If there are no comments, enter N/A) .5",Overall Satisfaction,Scale .6,"Comment (If there are no comments, enter N/A) .6"
0,nan,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,...,Did the project manager identify value enginee...,nan,"Did the project manager effectively identify, ...","Did the project manager effectively identify, ...",nan,Did the project manager act with a satisfactor...,Did the project manager act with a satisfactor...,nan,Please provide your overall satisfaction ratin...,Please provide your overall satisfaction ratin...
1,23487607.000,204.63.44.148,5/16/2017 14:03,False,167.000,1.000,nan,nan,nan,nan,...,Creativity In resolving vendor issues with sec...,nan,5,NaN,nan,NaN,NaN,nan,5,NaN
2,23487700.000,204.63.44.148,5/16/2017 14:06,False,113.000,1.000,nan,nan,nan,nan,...,NaN,nan,5,NaN,nan,NaN,NaN,nan,5,NaN
3,23487756.000,204.63.44.148,5/16/2017 14:09,False,103.000,1.000,nan,nan,nan,nan,...,NaN,nan,5,NaN,nan,NaN,NaN,nan,5,NaN
4,23487783.000,199.244.214.112,5/16/2017 14:11,False,236.000,1.000,nan,nan,nan,nan,...,NaN,nan,4,NaN,nan,NaN,NaN,nan,5,NaN

In [4]:
data = data.loc[1:, :]

In [5]:
data.columns

Index(['Response ID', 'IP Address', 'Timestamp (MM/dd/yyyy)', 'Duplicate',
       'Time Taken to Complete (Seconds)', 'Seq. Number', 'External Reference',
       'Custom Variable 1', 'Custom Variable 2', 'Custom Variable 3',
       'Custom Variable 4', 'Custom Variable 5', 'Respondent Email',
       'Email List', 'Country Code', 'Region', '1 - Q4', '2 - Q1',
       '3 - OVP Project Number', '4 - Client Surveyor Name', '5 - Q5',
       'Schedule Adherence', 'Scale ',
       'Comment (If there are no comments, enter N/A) ', 'Budget Adherence',
       'Scale .1', 'Comment (If there are no comments, enter N/A) .1',
       'Scope Adherence', 'Scale .2',
       'Comment (If there are no comments, enter N/A) .2',
       'Value and Innovation', 'Scale .3',
       'Comment (If there are no comments, enter N/A) .3', 'Risk', 'Scale .4',
       'Comment (If there are no comments, enter N/A) .4', 'Professionalism',
       'Scale .5', 'Comment (If there are no comments, enter N/A) .5',
       'Overall Satisfaction', 'Scale .6',
       'Comment (If there are no comments, enter N/A) .6'],
      dtype='object')

In [6]:
data = data.loc[:, ['Response ID', 'Timestamp (MM/dd/yyyy)', 
       '3 - OVP Project Number', '4 - Client Surveyor Name', 'Scale ',
       'Comment (If there are no comments, enter N/A) ',
       'Scale .1', 'Comment (If there are no comments, enter N/A) .1', 'Scale .2',
       'Comment (If there are no comments, enter N/A) .2',
        'Scale .3',
       'Comment (If there are no comments, enter N/A) .3', 'Scale .4',
       'Comment (If there are no comments, enter N/A) .4',
       'Scale .5', 'Comment (If there are no comments, enter N/A) .5',
     'Scale .6',
       'Comment (If there are no comments, enter N/A) .6']]

In [7]:
data.rename(columns ={'Scale ' : 'Schedule Adherence',
                      'Comment (If there are no comments, enter N/A) ' :  'Schedule Adherence Comment',
                    'Scale .1' : 'Budget Adherence',
                      'Comment (If there are no comments, enter N/A) .1' : 'Budget Adherence Comment',
                      'Scale .2' : 'Scope Adherence',
                   'Comment (If there are no comments, enter N/A) .2' : 'Scope Adherence Comment',
                    'Scale .3' : 'Value and Innovation',
                   'Comment (If there are no comments, enter N/A) .3' : 'Value and Innovation Comment',
                      'Scale .4' : 'Risk',
                   'Comment (If there are no comments, enter N/A) .4' : 'Risk Comment',
                   'Scale .5' : 'Professionalism', 'Comment (If there are no comments, enter N/A) .5' : 'Professionalism Comment',
                     'Scale .6' : 'Overall Satisfaction',
                   'Comment (If there are no comments, enter N/A) .6': 'Overall Satisfaction Comment' }, inplace=True)

In [8]:
data.columns

Index(['Response ID', 'Timestamp (MM/dd/yyyy)', '3 - OVP Project Number',
       '4 - Client Surveyor Name', 'Schedule Adherence',
       'Schedule Adherence Comment', 'Budget Adherence',
       'Budget Adherence Comment', 'Scope Adherence',
       'Scope Adherence Comment', 'Value and Innovation',
       'Value and Innovation Comment', 'Risk', 'Risk Comment',
       'Professionalism', 'Professionalism Comment', 'Overall Satisfaction',
       'Overall Satisfaction Comment'],
      dtype='object')

In [9]:
held_out = data[data['3 - OVP Project Number'].isin(['00063P160081', '00063P153405', '00063P160044', '00063P161041']) ]

In [10]:
data.dropna(subset=[ 'Schedule Adherence',
        'Budget Adherence',
        'Scope Adherence',
        'Value and Innovation',
       'Risk', 
       'Professionalism', 'Overall Satisfaction',
       ], inplace=True)

In [11]:
data.head()

,Response ID,Timestamp (MM/dd/yyyy),3 - OVP Project Number,4 - Client Surveyor Name,Schedule Adherence,Schedule Adherence Comment,Budget Adherence,Budget Adherence Comment,Scope Adherence,Scope Adherence Comment,Value and Innovation,Value and Innovation Comment,Risk,Risk Comment,Professionalism,Professionalism Comment,Overall Satisfaction,Overall Satisfaction Comment
7,24539970.000,6/20/2017 13:50,00063P160768,Lindsey Stem,3,NaN,4,NaN,5,LOB was very satisfied with the work and reque...,4,NaN,3,NaN,5,NaN,5,The LOB was demanding and was satisfied with W...
12,25446868.000,7/24/2017 10:56,00063P160183,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
13,25447721.000,7/24/2017 11:32,00063P160102,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
15,25500441.000,7/26/2017 8:22,00063P153284,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
16,25500615.000,7/26/2017 8:27,00063P152806,David Gensemer,2,The project schedule was not met and had to be...,1,NaN,2,NaN,3,NaN,1,Risks to schedule and budget were not identifi...,2,The project manager did not act with professio...,1,NaN

In [12]:
data.describe()

       Response ID
count       23.000
mean  25473347.174
std     221460.694
min   24539970.000
25%   25501104.000
50%   25501620.000
75%   25503773.500
max   25909860.000

In [13]:
data = data.append(held_out)

In [14]:
data.describe()

       Response ID
count       27.000
mean  25194036.556
std     715523.546
min   23487607.000
25%   25474081.000
50%   25501471.000
75%   25503652.500
max   25909860.000

In [15]:
data

,Response ID,Timestamp (MM/dd/yyyy),3 - OVP Project Number,4 - Client Surveyor Name,Schedule Adherence,Schedule Adherence Comment,Budget Adherence,Budget Adherence Comment,Scope Adherence,Scope Adherence Comment,Value and Innovation,Value and Innovation Comment,Risk,Risk Comment,Professionalism,Professionalism Comment,Overall Satisfaction,Overall Satisfaction Comment
7,24539970.000,6/20/2017 13:50,00063P160768,Lindsey Stem,3,NaN,4,NaN,5,LOB was very satisfied with the work and reque...,4,NaN,3,NaN,5,NaN,5,The LOB was demanding and was satisfied with W...
12,25446868.000,7/24/2017 10:56,00063P160183,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
13,25447721.000,7/24/2017 11:32,00063P160102,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
15,25500441.000,7/26/2017 8:22,00063P153284,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
16,25500615.000,7/26/2017 8:27,00063P152806,David Gensemer,2,The project schedule was not met and had to be...,1,NaN,2,NaN,3,NaN,1,Risks to schedule and budget were not identifi...,2,The project manager did not act with professio...,1,NaN
19,25501057.000,7/26/2017 8:40,00063P161658,David Gensemer,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN
21,25501151.000,7/26/2017 8:43,00063P160149,David Gensemer,3,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,3,NaN
22,25501283.000,7/26/2017 8:47,00063P160618,David Gensemer,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN
23,25501336.000,7/26/2017 8:49,00063P160910,David Gensemer,5,Project well managed to a very tight schedule.,5,Project well managed to a tight budget.,5,NaN,4,NaN,4,PM kept the team moving by anticipating hurdle...,5,PM acted with a very high degree of profession...,5,NaN
24,25501471.000,7/26/2017 8:55,00063P160475,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
25,25501531.000,7/26/2017 8:57,00063P160717,David Gensemer,4,PM did a solid job of delivering the project o...,4,NaN,4,Delivered per scope.,4,NaN,4,NaN,4,NaN,4,NaN
26,25501620.000,7/26/2017 9:01,00063P160841,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
27,25501665.000,7/26/2017 9:03,00063P153200,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
28,25501706.000,7/26/2017 9:05,00063P152711,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
29,25501756.000,7/26/2017 9:08,00063P152117,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
30,25503596.000,7/26/2017 10:16,00063P160472,Hannah French,4,n/a,5,n/a,5,n/a,5,n/a,5,n/a,5,n/a,5,n/a
33,25503709.000,7/26/2017 10:20,00063P160629,Hannah French,5,n/a,5,n/a,5,n/a,4,n/a,5,n/a,5,n/a,5,n/a
36,25503838.000,7/26/2017 10:27,00063P160417,Hannah French,2,n/a,4,n/a,4,n/a,4,n/a,4,n/a,5,n/a,4,n/a
37,25503881.000,7/26/2017 10:28,00063P160579,Hannah French,4,n/a,5,n/a,5,n/a,4,n/a,4,n/a,5,n/a,5,n/a
38,25503909.000,7/26/2017 10:30,00063P160771,Hannah French,5,n/a,5,n/a,4,n/a,4,n/a,4,n/a,5,n/a,5,n/a
40,25503986.000,7/26/2017 10:33,00063P160419,Hannah French,4,n/a,5,n/a,5,n/a,4,n/a,5,n/a,5,n/a,5,n/a
41,25504015.000,7/26/2017 10:35,00063P161167,Hannah French,3,Project schedule took longer than anticipated ...,3,By using a GC instead of contracting directly ...,4,n/a,3,Project followed an overly conservative plan t...,4,n/a,5,n/a,3,Overall satisfaction is affected by increased ...
42,25909860.000,8/11/2017 11:59,00063P153273,Erin Mical,4,NaN,5,NaN,3,Exactly what client asked. Not quite above exp...,4,NaN,4,NaN,5,NaN,4,Thru this project is was great to see Will's p...
1,23487607.000,5/16/2017 14:03,00063P160081,Patrick Fernandez,4,NaN,5,NaN,4,NaN,4,Creativity In resolving vendor issues with sec...,5,NaN,NaN,NaN,5,NaN
4,23487783.000,5/16/2017 14:11,00063P153405,Patrick Fernandez,2,Project exceeded original planned schedule exp...,4,Budget became a challenge due to mixed communi...,4,NaN,4,NaN,4,NaN,NaN,NaN,5,NaN
5,23487866.000,5/16/2017 14:16,00063P160044,Patrick Fernandez,4,NaN,4,NaN,5,NaN,5,NaN,5,NaN,NaN,NaN,5,NaN
6,23888746.000,5/26/2017 9:18,00063P161041,Adriana Nino,5,NaN,5,NaN,5,NaN,2,There are opportunities fro improvement in fee...,3,NaN,NaN,NaN,4,Continue to exercise articulation and eloquenc...

In [19]:
data.loc[data['3 - OVP Project Number'] == '00063P160081', 'Professionalism'] = 5
data.loc[data['3 - OVP Project Number'] == '00063P153405', 'Professionalism'] = 5
data.loc[data['3 - OVP Project Number'] == '00063P160044', 'Professionalism'] = 5
data.loc[data['3 - OVP Project Number'] == '00063P161041', 'Professionalism'] = 5

In [18]:
data

,Response ID,Timestamp (MM/dd/yyyy),3 - OVP Project Number,4 - Client Surveyor Name,Schedule Adherence,Schedule Adherence Comment,Budget Adherence,Budget Adherence Comment,Scope Adherence,Scope Adherence Comment,Value and Innovation,Value and Innovation Comment,Risk,Risk Comment,Professionalism,Professionalism Comment,Overall Satisfaction,Overall Satisfaction Comment
7,24539970.000,6/20/2017 13:50,00063P160768,Lindsey Stem,3,NaN,4,NaN,5,LOB was very satisfied with the work and reque...,4,NaN,3,NaN,5,NaN,5,The LOB was demanding and was satisfied with W...
12,25446868.000,7/24/2017 10:56,00063P160183,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
13,25447721.000,7/24/2017 11:32,00063P160102,Ted Tremain,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
15,25500441.000,7/26/2017 8:22,00063P153284,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
16,25500615.000,7/26/2017 8:27,00063P152806,David Gensemer,2,The project schedule was not met and had to be...,1,NaN,2,NaN,3,NaN,1,Risks to schedule and budget were not identifi...,2,The project manager did not act with professio...,1,NaN
19,25501057.000,7/26/2017 8:40,00063P161658,David Gensemer,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN
21,25501151.000,7/26/2017 8:43,00063P160149,David Gensemer,3,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,3,NaN
22,25501283.000,7/26/2017 8:47,00063P160618,David Gensemer,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN,4,NaN
23,25501336.000,7/26/2017 8:49,00063P160910,David Gensemer,5,Project well managed to a very tight schedule.,5,Project well managed to a tight budget.,5,NaN,4,NaN,4,PM kept the team moving by anticipating hurdle...,5,PM acted with a very high degree of profession...,5,NaN
24,25501471.000,7/26/2017 8:55,00063P160475,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
25,25501531.000,7/26/2017 8:57,00063P160717,David Gensemer,4,PM did a solid job of delivering the project o...,4,NaN,4,Delivered per scope.,4,NaN,4,NaN,4,NaN,4,NaN
26,25501620.000,7/26/2017 9:01,00063P160841,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
27,25501665.000,7/26/2017 9:03,00063P153200,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
28,25501706.000,7/26/2017 9:05,00063P152711,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
29,25501756.000,7/26/2017 9:08,00063P152117,David Gensemer,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN,3,NaN
30,25503596.000,7/26/2017 10:16,00063P160472,Hannah French,4,n/a,5,n/a,5,n/a,5,n/a,5,n/a,5,n/a,5,n/a
33,25503709.000,7/26/2017 10:20,00063P160629,Hannah French,5,n/a,5,n/a,5,n/a,4,n/a,5,n/a,5,n/a,5,n/a
36,25503838.000,7/26/2017 10:27,00063P160417,Hannah French,2,n/a,4,n/a,4,n/a,4,n/a,4,n/a,5,n/a,4,n/a
37,25503881.000,7/26/2017 10:28,00063P160579,Hannah French,4,n/a,5,n/a,5,n/a,4,n/a,4,n/a,5,n/a,5,n/a
38,25503909.000,7/26/2017 10:30,00063P160771,Hannah French,5,n/a,5,n/a,4,n/a,4,n/a,4,n/a,5,n/a,5,n/a
40,25503986.000,7/26/2017 10:33,00063P160419,Hannah French,4,n/a,5,n/a,5,n/a,4,n/a,5,n/a,5,n/a,5,n/a
41,25504015.000,7/26/2017 10:35,00063P161167,Hannah French,3,Project schedule took longer than anticipated ...,3,By using a GC instead of contracting directly ...,4,n/a,3,Project followed an overly conservative plan t...,4,n/a,5,n/a,3,Overall satisfaction is affected by increased ...
42,25909860.000,8/11/2017 11:59,00063P153273,Erin Mical,4,NaN,5,NaN,3,Exactly what client asked. Not quite above exp...,4,NaN,4,NaN,5,NaN,4,Thru this project is was great to see Will's p...
1,23487607.000,5/16/2017 14:03,00063P160081,Patrick Fernandez,4,NaN,5,NaN,4,NaN,4,Creativity In resolving vendor issues with sec...,5,NaN,5,NaN,5,NaN
4,23487783.000,5/16/2017 14:11,00063P153405,Patrick Fernandez,2,Project exceeded original planned schedule exp...,4,Budget became a challenge due to mixed communi...,4,NaN,4,NaN,4,NaN,NaN,NaN,5,NaN
5,23487866.000,5/16/2017 14:16,00063P160044,Patrick Fernandez,4,NaN,4,NaN,5,NaN,5,NaN,5,NaN,NaN,NaN,5,NaN
6,23888746.000,5/26/2017 9:18,00063P161041,Adriana Nino,5,NaN,5,NaN,5,NaN,2,There are opportunities fro improvement in fee...,3,NaN,NaN,NaN,4,Continue to exercise articulation and eloquenc...

In [23]:
data.describe(include='all')

,Response ID,Timestamp (MM/dd/yyyy),3 - OVP Project Number,4 - Client Surveyor Name,Schedule Adherence,Schedule Adherence Comment,Budget Adherence,Budget Adherence Comment,Scope Adherence,Scope Adherence Comment,Value and Innovation,Value and Innovation Comment,Risk,Risk Comment,Professionalism,Professionalism Comment,Overall Satisfaction,Overall Satisfaction Comment
count,27.000,27,27,27,27,11,27,9,27,10,27,9,27,9,27,9,27,10
unique,nan,27,27,7,4,6,4,4,4,4,4,4,4,3,5,3,4,5
top,nan,7/26/2017 9:05,00063P161658,David Gensemer,3,n/a,5,n/a,3,n/a,4,n/a,4,n/a,5,n/a,3,n/a
freq,nan,1,1,12,11,6,9,6,9,7,14,6,11,7,10,7,10,6
mean,25194036.556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,715523.546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,23487607.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,25474081.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,25501471.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,25503652.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,25909860.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
data.columns

Index(['Response ID', 'Timestamp (MM/dd/yyyy)', '3 - OVP Project Number',
       '4 - Client Surveyor Name', 'Schedule Adherence',
       'Schedule Adherence Comment', 'Budget Adherence',
       'Budget Adherence Comment', 'Scope Adherence',
       'Scope Adherence Comment', 'Value and Innovation',
       'Value and Innovation Comment', 'Risk', 'Risk Comment',
       'Professionalism', 'Professionalism Comment', 'Overall Satisfaction',
       'Overall Satisfaction Comment'],
      dtype='object')

In [25]:
for x in ['Schedule Adherence',
       'Budget Adherence',
        'Scope Adherence',
        'Value and Innovation',
       'Risk', 
       'Professionalism','Overall Satisfaction']:
    data[x] = data[x].astype(int)

In [26]:
data.describe()

,Response ID,Schedule Adherence,Budget Adherence,Scope Adherence,Value and Innovation,Risk,Professionalism,Overall Satisfaction
count,27.000,27.000,27.000,27.000,27.000,27.000,27.000,27.000
mean,25194036.556,3.519,3.889,3.889,3.630,3.704,4.148,3.889
std,715523.546,0.893,1.013,0.892,0.688,0.912,0.989,1.050
min,23487607.000,2.000,1.000,2.000,2.000,1.000,2.000,1.000
25%,25474081.000,3.000,3.000,3.000,3.000,3.000,3.000,3.000
50%,25501471.000,3.000,4.000,4.000,4.000,4.000,5.000,4.000
75%,25503652.500,4.000,5.000,5.000,4.000,4.000,5.000,5.000
max,25909860.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000

In [33]:
data.to_csv('Transformed.csv')